version: '3.9'

services:
  postgres:
    image: postgres:latest
    volumes:
      - .:/Bookmark
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
  web:
    tty: true
    build:
      context: .
    command: >
            sh -c "python manage.py makemigrations &&
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/Bookmark
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
